name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Node Dependencies
        run: |
          echo "Installing node dependencies..."
          npm ci

      - name: Build Application
        run: |
          echo "Building application"
          npm run build
