name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install Node Dependencies
        run: |
          echo "Installing node dependencies..."
          npm ci

      - name: Build Application
        run: |
          echo "Building application"
          npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-24.04
    environment: AWS
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: portfolio-dist
          path: dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload Assets to S3
        env:
          BUCKET_NAME: ${{ vars.S3_BUCKET_NAME }}
        run: |
          set -u

          echo "Uploading frontend assets to S3..."
          aws s3 sync dist/portfolio/browser s3://$S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront Distribution
        env:
          CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
        run: |
          set -u

          echo "Invalidating CloudFront distribution..."
          aws cloudfront create-invalidation \
            --distribution-id $CF_DISTRIBUTION_ID \
            --paths "/*"
